import React from "react";
import "./Layout.css"
class Structure extends React.Component {
  constructor(props){
    super(props)
  }
  render(){
  return (
    <div className="frame">
      <div className="calculator">
        <br />
        <div>
          <input
            type="text"
            readOnly
            className="screen"
            style={{ textSize: "40px" }}
            value={0}
          />
        </div>
        <div className="keys">
          <input
            type="button"
            value="AC"
            className="button-clear"
          />
          <input
            type="button"
            value="+/-"
            className="button-operator"
          />
          <input
            type="button"
            value="%"
            className="button-operator"
          />
          <input
            type="button"
            value="&#247;"
            className="button-operator"
            id="red"
          />
          <input
            type="button"
            value="7"
            className="button-operator"
          />
          <input
            type="button"
            value="8"
            className="button-operator"
          />
          <input
            type="button"
            value="9"
            className="button-operator"
          />
          <input
            type="button"
            value="*"
            className="button-operator"
            id="red"
          />
          <input
            type="button"
            value="4"
            className="button-operator"
          />
          <input
            type="button"
            value="5"
            className="button-operator"
          />
          <input
            type="button"
            value="6"
            className="button-operator"
          />
          <input
            type="button"
            value="-"
            className="button-operator"
            id="red"
          />
          <input
            type="button"
            value="1"
            className="button-operator"
          />
          <input
            type="button"
            value="2"
            className="button-operator"
          />
          <input
            type="button"
            value="3"
            className="button-operator"
          />
          <input
            type="button"
            value="+"
            className="button-operator"
            id="red"
          />

          <input
            type="button"
            value="0"
            className="button-operator"
            id="blue"
          />
          <input
            type="button"
            value="."
            className="button-operator"
          />
          <input
            type="button"
            value="="
            className="button-operator"
            id="red"
          />
        </div>
      </div>
    </div>
  );
  }
};

export default Structure;
